SELECT FO.PRODUCT_ID, FP.PRODUCT_NAME, FP.PRICE * SUM(AMOUNT) AS TOTAL_SALES
FROM FOOD_ORDER AS FO
JOIN FOOD_PRODUCT AS FP
    ON FO.PRODUCT_ID = FP.PRODUCT_ID
WHERE DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'
GROUP BY FO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, FO.PRODUCT_ID;