SELECT DATE_FORMAT(START_DATE, '%m') AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE DATE_FORMAT(START_DATE, '%m') BETWEEN 08 AND 10
    AND CAR_ID IN
        (SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE DATE_FORMAT(START_DATE, '%m') BETWEEN 08 AND 10
        GROUP BY CAR_ID
        HAVING COUNT(CAR_ID) >= 5 )
GROUP BY DATE_FORMAT(START_DATE, '%m'), CAR_ID
ORDER BY DATE_FORMAT(START_DATE, '%m') ASC, CAR_ID DESC;