SELECT PRODUCT_CODE, 
    SUM(PRICE*SALES_AMOUNT) AS SALES
FROM PRODUCT JOIN OFFLINE_SALE USING(PRODUCT_ID)
GROUP BY PRODUCT_CODE
ORDER BY SUM(PRICE*SALES_AMOUNT) DESC, PRODUCT_CODE;

SELECT
    P.PRODUCT_CODE,
    SUM(P.PRICE*O.SALES_AMOUNT) AS SALES
FROM PRODUCT P
    JOIN OFFLINE_SALE O
    USING(PRODUCT_ID)
GROUP BY 1
ORDER BY 2 DESC, 1;