SELECT BOOK.AUTHOR_ID,
    AUTHOR.AUTHOR_NAME,
    BOOK.CATEGORY,
    SUM(BOOK_SALES.SALES*BOOK.PRICE) AS TOTAL_SALES
FROM BOOK JOIN AUTHOR USING(AUTHOR_ID)
    JOIN BOOK_SALES USING(BOOK_ID)
WHERE SUBSTRING(BOOK_SALES.SALES_DATE, 1, 7) = '2022-01'
GROUP BY BOOK.AUTHOR_ID, BOOK.CATEGORY
ORDER BY AUTHOR_ID, CATEGORY DESC;