SELECT CAR_TYPE,
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK JOIN AUTHOR USING(AUTHOR_ID)
WHERE CATEGORY ='경제'
ORDER BY PUBLISHED_DATE;

SELECT
    B.BOOK_ID,
    A.AUTHOR_NAME,
    DATE_FORMAT(B.PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK B
    JOIN AUTHOR A
    USING(AUTHOR_ID)
WHERE B.CATEGORY LIKE '경제'
ORDER BY 3;